# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mathew Rupp
email: mathewrupp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Keeping It Real Since 1988.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cybnew.github.io/mrupp-blog/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Mathewrupp
github_username:  Cybnew

# Build settings
markdown: kramdown
#theme: jekyll-theme-so-simple
theme: jekyll-theme-cayman
#remote_theme: "mmistakes/so-simple-theme"

locale: en-US
plugins:
  - jekyll-feed
# mathjax: true

# read_time: true
# words_per_minute: 200
# search_full_content: true

# google_fonts:
#   - name: "Source Sans Pro"
#     weights: "400,400i,700,700i"
#   - name: "Lora"
#     weights: "400,400i,700,700i"

# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# defaults:
#   # Post defaults
#   - scope:
#       path: "_posts"
#       type: posts
#     values:
#       layout: post
#       comments: true
#       share: true
#   # Recipe defaults
#   - scope:
#       path: "_recipes"
#       type: recipes
#     values:
#       layout: post
#       comments: true
#       share: true

# # Site Author
# author: 
#   name: Mathew Rupp
#   picture: /images/IMG-1995.jpg
#   email: mathewrupp@gmail.com
#   twitter: MathewRupp
#   links:
#     - title: Twitter
#       url: https://twitter.com/mmistakes
#       icon: fab fa-twitter-square
#     - title: Instagram
#       url: https://instagram.com/mmistakes
#       icon: fab fa-instagram
#     - title: GitHub
#       url: https://github.com/mmistakes
#       icon: fab fa-github-square


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
